### ISSUE TITLE
command not running from command handler

### ISSUE THREAD

**Issue by datNurd** [limetext/commands#66]
I've recently started writing code to new commands, in this process I've observed a new confusing issue.

I've written code to replace all occurrences of a text, the command work fine when I create a pointer to the command and call the run on the pointer, if I run the same command through CommandHandler it doesnt work

Works :-
```
r := &commands.ReplaceAll{SearchText: []rune("hello"), ReplaceText: []rune("hello2")}
r.Run(v,e)
```

Doesnt work  (The function itelf is not called, I have a print inside the replace_all which is not called ) :-
```
ch := ed.CommandHandler()
ch.RunTextCommand(v, "replace_all", backend.Args{"search_text":[]rune("hello"),"replace_text": []rune("hello2")})
```

Now the interesting part :
If I call some other command from the package and then call the ReplaceAll through command handler the ReplaceAll magically executes

Works:-
```
c := &commands.FindAll{SearchText: []rune("hello")}
c.Run(v,e)
ch := ed.CommandHandler()
ch.RunTextCommand(v, "replace_all", backend.Args{"search_text":[]rune("hello"),"replace_text": []rune("hello2")})

```
The replace_all which did not work (get called) when called standalone, starts working(Called) now when I called it in combination with some other function from the same package.

**Comment by zoli** [comment]
Can I see how is your command implemented? Also have you seen the tests? they might help.

**Comment by datNurd** [comment]
Yes, I've seen and implemented the tests, thats when I realized the function is not getting called in first place. Then I started testing by calling the command in the main package that's when I discovered this confusing pattern that I've highlighted above.

Implementation:
```
type(
    ReplaceAll struct{
		backend.DefaultCommand
		SearchText []rune
		ReplaceText []rune
	}
)
func (c *ReplaceAll) Run(v *backend.View, e *backend.Edit) error{
	last := 0
	search := string(c.SearchText)
	replace := string(c.ReplaceText)
	fmt.Println("Called")
	sel := v.Sel() 
	sel.Clear()
	r := text.Region{-1,-1}
	for {
		r = v.Find(search,last,backend.IGNORECASE|backend.LITERAL);
		if r.A == -1 {
			break
		}
		v.Erase(e, r)
		v.Insert(e, r.Begin(), replace)
		last = r.B
	}
	return nil
}

func init() {
	register([]backend.Command{
		&ReplaceAll{},
	})
}

```
call : - 

```
ch := ed.CommandHandler()
	ch.RunTextCommand(v, "replace_all", backend.Args{"search_text":[]rune("hello"),"replace_text": []rune("hello2")})
	ch.RunTextCommand(v,"find_all",nil)

```

**Comment by datNurd** [comment]
I think I have finally figured out what has happened, there was a flaw in the way I was running tests. Was able to figure it out from this [post](https://stackoverflow.com/questions/16935965/how-to-run-test-cases-in-a-specified-file ) . I was not specifying the file required to build the test, due to which the init function wasn't being called and therefore not registering the command.

**Comment by zoli** [comment]
Glad to hear that, so we should close this?

**Comment by datNurd** [comment]
Closed
